### ISSUE TITLE
"Open Source" and "Free Software"

### ISSUE THREAD

**Issue by cyphar** [SUSE/suse.github.io#9]
I usually don't make a big deal of my choice of wording in this department. However, I think this is something we should at least *address*.

Open Source and Free Software are two different movements with different driving forces. My personal choice is the Free Software movement -- where **user freedom** is the primary motivation and concern. Open Source bills itself based on technical merit (which in my opinion is a side-effect, not the purpose of the Free Software movement).

So, I'd like to clarify whether we should be referring to the stuff we're working on as "open source" or "free software" -- especially between each other. Maybe it would be "bad marketing", but the whole point of this is that we are trying to put forward how we (as engineers) see the world.

**Comment by cornelius** [comment]
Personally I agree with you. The ideals of free software are what is driving me. That said, in the space where SUSE operates "open source" is kind of the standard term and we use that pretty consistently in our communication. The audience we are trying to reach is much bigger than those who know the difference between free software and open source, so in order to not confuse people and to have an effective communication using the terms people already know, I think it's best to use the term "open source" here.

**Comment by hennevogel** [comment]
Can we put this on the agenda of the next meeting and discuss it there? I might have an opinion ;-)

**Comment by okurz** [comment]
As long as there is no need to decide for one or the other, FOSS might be a better term…

**Comment by hennevogel** [comment]
In the meeting we just had we decided that we should do 2 things about this on the page:

* Explain where we see the difference between Open Source and Free Software  #(#11)
* Explain our collective (SUSE engineering) preference which is Free Software (#12)

This should cover this
